### ISSUE TITLE
Templates not nested correctly

### ISSUE THREAD

**Issue by dblessing** [poise/poise-service-runit#2]
I believe not having templates nested in a sub-dir like `default` is causing the following error on `berks upload`:

```
build	25-Aug-2015 14:20:31	E, [2015-08-25T14:20:31.676557 #4979] ERROR -- : Ridley::Errors::HTTPBadRequest: {"error":["Invalid element in array value of 'templates'."]}
build	25-Aug-2015 14:20:31	E, [2015-08-25T14:20:31.676769 #4979] ERROR -- : /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/middleware/chef_response.rb:24:in `on_complete'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/middleware/chef_auth.rb:74:in `call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/request/retry.rb:110:in `call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/connection.rb:106:in `run_request'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `put'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
build	25-Aug-2015 14:20:31	(celluloid):0:in `remote procedure call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
build	25-Aug-2015 14:20:31	(celluloid):0:in `remote procedure call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/resource.rb:132:in `raw_request'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/resource.rb:123:in `request'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/resources/cookbook_resource.rb:162:in `update'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/resources/cookbook_resource.rb:230:in `upload'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
build	25-Aug-2015 14:20:31	(celluloid):0:in `remote procedure call'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:55:in `block (2 levels) in upload'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:51:in `each'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:51:in `block in upload'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/client.rb:38:in `open'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley.rb:51:in `open'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf.rb:144:in `ridley_connection'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:50:in `upload'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:37:in `run'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:545:in `upload'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:208:in `upload'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
build	25-Aug-2015 14:20:31	/opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
build	25-Aug-2015 14:20:31	/usr/bin/berks:43:in `load'
build	25-Aug-2015 14:20:31	/usr/bin/berks:43:in `<main>'
```

**Comment by coderanger** [comment]
This was a bug in Ridley that was fixed long ago.

**Comment by dblessing** [comment]
Thanks. I hit 'submit' and you responded on chat. I'll give berks upgrade a try.
